version: '3.8'

volumes:
  milton-castro-ssys-test:

services:
  db:
    container_name: 'ssys-test-db'
    image: mysql:5.7.31
    command: --default-authentication-plugin=mysql_native_password --sql_mode=NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER --explicit_defaults_for_timestamp
    restart: unless-stopped
    ports:
      - $MYSQL_PORT:$MYSQL_PORT
    expose:
      - $MYSQL_PORT
    volumes:
      - milton-castro-ssys-test:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DB_NAME
      - TZ=America/Sao_Paulo

  app:
    container_name: 'ssys-test-app'
    image: milton-castro-ssys-test
    build: ./
    env_file:
      - ./.env
    command: npm start
    ports:
      - $SERVER_PORT:$SERVER_PORT
    links:
      - db
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DB_NAME=$MYSQL_DB_NAME
      - MYSQL_PORT=$MYSQL_PORT
      - WAIT_HOSTS=db:$MYSQL_PORT